export async function createActorFromData(npcData) {
    if (!npcData || !npcData.name) {
        throw new Error("Invalid NPC Data provided to Actor Creator.");
    }

    console.log("FFXIV TTRPG Generator | Creating Actor from AI Data:", npcData);

    // =========================================================================
    // IMPORTANT: FOUNDRY SYSTEM DATA MAPPING
    // Since we don't know the exact internal variable names of the user's
    // specific FFXIV TTRPG module/system, we use a generic mapping approach.
    // The user will need to adjust these paths if they don't match their system.
    // =========================================================================

    const actorData = {
        name: npcData.name,
        type: "npc", // Might need to be "character", "monster", or whatever the system uses
        img: "icons/svg/mystery-man.svg", // Default image
        system: {
            // These paths are highly speculative and depend entirely on the installed system.
            // Example mapping assuming a relatively standard layout:
            attributes: {
                level: { value: npcData.level || 1 },
                str: { value: npcData.attributes?.str || 10 },
                dex: { value: npcData.attributes?.dex || 10 },
                vit: { value: npcData.attributes?.vit || 10 },
                int: { value: npcData.attributes?.int || 10 },
                mnd: { value: npcData.attributes?.mnd || 10 },
                hp: { value: npcData.secondary?.maxHp || 100, max: npcData.secondary?.maxHp || 100 },
                mp: { value: npcData.secondary?.maxMp || 0, max: npcData.secondary?.maxMp || 0 },
                defense: { value: npcData.secondary?.defense || 10 },
                magicDefense: { value: npcData.secondary?.magicDefense || 10 },
                vigilance: { value: npcData.secondary?.vigilance || 10 },
                speed: { value: npcData.secondary?.speed || 6 }
            },
            details: {
                biography: { value: npcData.description || "Generated by AI." }
            }
        }
    };

    // Create the actor
    const newActor = await Actor.create(actorData);

    if (newActor) {
        console.log(`FFXIV TTRPG Generator | Successfully created Actor '${newActor.name}' [${newActor.id}]`);
        // Optionally open the sheet immediately
        newActor.sheet.render(true);
    } else {
        throw new Error("Foundry failed to create the Actor.");
    }
}
